### ISSUE TITLE
Can't Load Database: Unexpected end of JSON input

### ISSUE THREAD

**Issue by soenkegissel** [Belphemur/json-db-node-red#10]
If I unexpectedly power off my raspberry pi, after a reboot it can happen that this database will not work.
I get the following error. Maybe during the power off it was written to it. I need to remove the file.

**20 Feb 19:55:47 - [error] [DataIn:a4b05396bf5dc9ac] DatabaseError: Can't Load Database:
SyntaxError: Unexpected end of JSON input**

Can a check be implemented for handling the Unexpected end of JSON input?

**Comment by Belphemur** [comment]
To be honest, there isn't much I can do.

if the file is corrupted, a human need to look at it and fix it. The corruption won't be always the same.
