### ISSUE TITLE
Merge data does not work 

### ISSUE THREAD

**Issue by tdullers** [Belphemur/json-db-node-red#4]
OK, please ignore this. I needed to define an array and now it works

Hi, 

The Merge data feature does not really seem to work for me. 
I created 2 Inject nodes that each inject different JSON data, I enabled the Merge feature but I always end up with a json file only containing the last injected value , never both values. 

Inject 1: { "_id": "57979e54b2917ca8999b0c82",     "index": 0,     "guid": "71c855bd-471e-4673-b29c-851763c4b109",     "isActive": true,     "balance": "$2,675.44",     "picture": "http://placehold.it/32x32",     "age": 28,     "eyeColor": "brown",     "name": "Gibbs Roth",     "gender": "male",     "company": "SARASONIC",     "email": "gibbsroth@sarasonic.com",     "phone": "+1 (860) 404-2663" }

Inject 2: {     "_id": "57979e54b667b3a72e003c21",     "index": 1,     "guid": "c5df8a71-2e42-4bab-9342-961c036fa48f",     "isActive": false,     "balance": "$2,443.16",     "picture": "http://placehold.it/32x32",     "age": 22,     "eyeColor": "blue",     "name": "Brandie Keller",     "gender": "female",     "company": "TOYLETRY",     "email": "brandiekeller@toyletry.com",     "phone": "+1 (960) 458-3931"   }

**Comment by Belphemur** [comment]
Merge will merge all the value in an Object. Which mean override each key that are the same and merge any array recursively.

Yes, if you're merging 2 arrays, it will append the value.

**Comment by DenDeze** [comment]
This topic is gold, saved me!
